
project_id = "szkhnwedzwvlqlktgvdp"

[functions.send-campaign-sms]
verify_jwt = false

[functions.generate-campaign-content]
verify_jwt = false

[functions.make-call]
verify_jwt = true

[functions.autocall-batch]
verify_jwt = true

[functions.smart-scrape]
verify_jwt = false
